# Generated by Django 5.0.3 on 2024-06-06 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarityDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similar_phrases', models.TextField()),
                ('identic_phrases', models.TextField()),
                ('similarity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_text', models.TextField()),
                ('second_text', models.TextField()),
                ('first_text_preprocessed', models.TextField(blank=True, null=True)),
                ('first_text_tokens', models.JSONField(blank=True, null=True)),
                ('second_text_preprocessed', models.TextField(blank=True, null=True)),
                ('second_text_tokens', models.JSONField(blank=True, null=True)),
                ('overall_similarity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cosine_similarity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cosine_similarity_comparisons', to='core.similaritydetails')),
                ('sequence_matcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequence_matcher_comparisons', to='core.similaritydetails')),
                ('wmdistance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wmdistance_comparisons', to='core.similaritydetails')),
            ],
        ),
    ]
